### ISSUE TITLE
Install ghc and cabal on flight

### ISSUE THREAD

**Issue by maxim-lobanov** [actions/setup-haskell#14]
Hello everyone!

Currently, this action switches ghc and cabal versions that are installed on the image.
Do you consider installation them in runtime during task execution?

So action will check if version is installed locally, if yes, it will just switch to it immediately (like it works right now). If not - version will be downloaded in runtime and installed firstly (with minor delay)

I think this approach will bring the following benefits:
1) Customers will be able to use new version of tool as soon as it is released. They won't need to wait until it is added to the image
2) Image will pre-cache only a few latest versions (the most popular) so we won't need to have all versions on the image.

Installation in runtime is not big deal:
- installation of `ghc` takes about 13-18 seconds
- installation of `cabal-install` takes 3 seconds

Currently, image contains a lot of versions of ghc and it is a bit painful because the size of each version is about 600MB-1000MB.
Old versions can't be deprecated because it will cause regression.
![image](https://user-images.githubusercontent.com/16715858/79886101-d8c6e000-8400-11ea-8834-612e11b9ac06.png)

**Comment by jared-w** [comment]
Version 1.1 of `setup-haskell` includes the ability to install versions of GHC, Cabal, and Stack that are not already installed locally.

**Comment by maxim-lobanov** [comment]
@jared-w , that is really great news!
What do you think about deprecation of old versions of ghc and cabal and keeping only N latest on the Ubuntu image? (Where N is about 2-3)
Currently, we have an issue on Ubuntu images with disk space (we can't afford to install new software and we had an incident with lack of disk space recently). So if it sounds good to you, we can do announcement and notify customers about it `we are planning to remove old versions of ghc / cabal from image in 2 weeks. If your use-case requires of using old version of these tools, please consider using actions/setup-haskel action. In future, we are planning to keep N latest versions on the image and they will be available immediately. Older versions can be accesses by action.`
cc: @alepauly

**Comment by jared-w** [comment]
@maxim-lobanov I'm certainly in favor of removing old versions of ghc from the Ubuntu images. In fact, I actually have an issue open in the actions/virtual-environments repo about this (and hopefully also adding ghc, cabal, and stack to macOS and Windows).

The convention for the Haskell ecosystem is to support the 3 latest point releases of ghc. Currently this would be GHC 8.10.x, 8.8.x, 8.6.x, where that would be 8.10.1, 8.8.3, 8.6.5 currently. If the images are very constrained for space, preinstalling the two most recent versions is almost always sufficient.

Of course, any adjustments to that could be made as a cost benefit trade-off if your metrics detect that you're burning a ton of cpu cycles reinstalling the same versions over and over.

A single install of the latest version of stack and cabal is also sufficient.

I'm personally biased in that I'd like to see ghc installed on windows and macOS if you're going to also go through and trim up Ubuntu, but either way is agreeable to me.

**Comment by tclem** [comment]
I'm also in favor of pruning down the list here. I thinking keeping the 3 latest point releases strikes a good balance and we can revisit if that's still too much stuff installed on the vm.

**Comment by maxim-lobanov** [comment]
@jared-w , I think you are talking about the issue https://github.com/actions/virtual-environments/issues/645 . It is on our backlog but we didn't start it yet because currently, we have some kind of freeze for new feature requests and we are mostly focused on improving stability of our images. (@alepauly , request looks pretty safe because it is just installation of new software. Any concerns to prioritize it?) 

The single concern from my side about deprecation is that Azure DevOps customers don't have setup-haskell action. (Is there something similar for them?).
These versions are pretty old and I don't think we will impact a lot of customers so 3 weeks will be good time to react.
We can post initial announcement in [virtual-environments](https://github.com/actions/virtual-environments) repository and then can push it to the GitHub blog if needs.
As for the announcement content, I think we can use something like that (please approve if it looks good to you):

## Deprecation of old Haskell, Cabal versions on Ubuntu images
Hello everyone,
Recently, [actions/setup-haskell v.1.1](https://github.com/actions/setup-haskell/releases/tag/v1.1.0) was released. This version started to support installation of Haskel, Cabal, Stack on-demand. Considering this fact, we are planning to deprecate of ghc, cabal from the image.
In future, we are planning to support 3 latest releases of ghc (currently, 8.10.1, 8.8.3, 8.6.5) and 1 latest release of cabal (currently, 3.2). All other versions can be installed in runtime using [actions/setup-haskell](https://github.com/actions/setup-haskell) action.
The full list of versions that will be deprecated:
- ghc: 8.0.2, 8.2.2, 8.4.4, 8.6.2, 8.6.3, 8.6.4, 8.8.1, 8.8.2
- cabal: 2.0, 2.2, 2.4, 3.0

These versions will be removed on May, 27. 
Please let us know if you have any concerns

**Comment by jared-w** [comment]
> I think you are talking about the issue actions/virtual-environments#645. It is on our backlog but we didn't start it yet because currently, we have some kind of freeze for new feature requests and we are mostly focused on improving stability of our images.

Yup, that's the one. No rush on it; even if all you do is remove the old versions of GHC on Linux, that'll still likely improve the stability as it'll shrink the image sizes down.

> The single concern from my side about deprecation is that Azure DevOps customers don't have setup-haskell action. (Is there something similar for them?).

I'm not familiar enough with Azure DevOps to know for sure, but from reading through the documentation, I did find that azure pipelines has the concept of [tool installer tasks](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/?view=azure-devops#tool). It seems like there's a potential for someone to implement something very similar to setup-haskell for azure pipelines, then?

However, like you said, the usage of old versions of GHC and Cabal is likely to be very low.

> As for the announcement content, I think we can use something like that

:+1: Your announcement message looks good to me; it's not missing anything important.

**Comment by alepauly** [comment]
> (@alepauly , request looks pretty safe because it is just installation of new software. Any concerns to prioritize it?)

sounds good to me

**Comment by maxim-lobanov** [comment]
Created announcement, thank you for your feedback!
Link: https://github.com/actions/virtual-environments/issues/852

**Comment by jared-w** [comment]
Awesome! Thanks! Should this issue be closed then?

**Comment by maxim-lobanov** [comment]
Yes, closing
