### ISSUE TITLE
Support GHC 8.8.4

### ISSUE THREAD

**Issue by niko2342** [actions/setup-haskell#28]
Please provide GHC version 8.8.4, which was released on July 27, 2020 (see https://www.haskell.org/ghc/blog/20200715-ghc-8.8.4-released.html).

**Comment by bubba** [comment]
Looks like there's a new release of ghcup which can now install ghc-8.8.4 https://gitlab.haskell.org/haskell/ghcup-hs/-/commit/97cd43792d301cc54059c03a1322e710268b37a6

**Comment by asr** [comment]
I couldn't use GHC 8.8.4. Could you release a new version including this fix, please.

**Comment by patrickt** [comment]
@asr Can you give us more information about what you encountered? “Couldn’t use” isn’t very helpful.

**Comment by bubba** [comment]
@patrickt I think they may have meant that there's no GitHub release with #29 in it yet, I've just been using the commit hash so far but it would be nice to have a minor version bump

**Comment by asr** [comment]
@patrickt, I got the following error using GitHub runner on Ubuntu (see GitHub [log](https://github.com/agda/agda/runs/990702236)): 

```
Run actions/setup-haskell@v1.1.2
with:
ghc-version: 8.8.4
...
Unable to locate package ghc-8.8.4
The process '/usr/bin/sudo' failed with exit code 100
```

**Comment by asr** [comment]
Any news?

**Comment by patrickt** [comment]
@asr We’re currently heads-down on some other projects; I’ll try to push out a release in the next couple weeks. For the time being, you can pin to a specific git version: `actions/setup-haskell@ 2215b2cb657e9dd555e7d634509d859983e7aa1e`.
