### ISSUE TITLE
Cabal 3.4.0 not available 

### ISSUE THREAD

**Issue by L-TChen** [actions/setup-haskell#45]
The current version of cabal provided by GitHub Actions is 3.4.0.0 instead of 3.3. https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md

This action downloads cabal 3.3.0.0 unnecessarily. Also, it doesn't seem necessary at all to download cabal if stack is used.

**Comment by neilmayhew** [comment]
Ideally, there would be another keyword like `latest` (eg `current`) that uses whatever version is in the runner's environment, and skips downloading anything.

I notice that Cabal 3.4.0.0 isn't even in the list of versions that this action knows about.

**Comment by ethercrow** [comment]
As far as I understand Cabal only has even numbers in the second position, so `3.0`, `3.2` and `3.4`: https://github.com/haskell/cabal/releases

**Comment by L-TChen** [comment]
Sorry for the confusion, I meant 3.4 is not available (not 3.3 stated in the subject previously).

**Comment by neilmayhew** [comment]
I updated #46 to omit 3.3

**Comment by L-TChen** [comment]
3.4 is not ready but only available as a prerelease on hva’s pap. Closing this issue now. See #46 for details.
