### ISSUE TITLE
Support Stack

### ISSUE THREAD

**Issue by ijks** [actions/setup-haskell#7]
[Stack] is a popular alternative to Cabal. From what I can tell this action does not support using it. Since cabal-install is no longer the only "default" package management & build tool for Haskell, it would be nice if Stack were also supported.

[Stack]: https://docs.haskellstack.org/en/stable/README/

**Comment by fosskers** [comment]
Note: https://github.com/mstksg/setup-stack

Usage: https://www.fosskers.ca/en/blog/github-ci

**Comment by ijks** [comment]
Great to see this resolved :)

**Comment by tclem** [comment]
Still need to cut an official release but using `actions/setup-haskell@master` can be used if you're eager.

**Comment by fosskers** [comment]
Fantastic! Thanks everyone.
